### ISSUE TITLE
Fix upload to PyPI from Appveyor with Python 3

### ISSUE THREAD

**Issue by taschini** [taschini/pycrlibm#1]
For release 1.0.3 I uploaded manually to PyPI  the *artifacts* generated by Appveyor for Python 3.

From the [Appveyor log](https://github.com/taschini/pycrlibm/files/306562/log.txt):

```
[00:01:19] running upload
[00:01:19] C:\Python35\lib\site-packages\wheel\pep425tags.py:77: RuntimeWarning: Config variable 'Py_DEBUG' is unset, Python ABI tag may be incorrect
[00:01:19]   warn=(impl == 'cp')):
[00:01:19] C:\Python35\lib\site-packages\wheel\pep425tags.py:81: RuntimeWarning: Config variable 'WITH_PYMALLOC' is unset, Python ABI tag may be incorrect
[00:01:19]   warn=(impl == 'cp')):
[00:01:19] Traceback (most recent call last):
[00:01:19]   File "setup.py", line 189, in <module>
[00:01:19]     setup(**metadata)
[00:01:19]   File "C:\Python35\lib\distutils\core.py", line 148, in setup
[00:01:19]     dist.run_commands()
[00:01:19]   File "C:\Python35\lib\distutils\dist.py", line 955, in run_commands
[00:01:19]     self.run_command(cmd)
[00:01:19]   File "C:\Python35\lib\distutils\dist.py", line 973, in run_command
[00:01:19]     cmd_obj.ensure_finalized()
[00:01:19]   File "C:\Python35\lib\distutils\cmd.py", line 107, in ensure_finalized
[00:01:19]     self.finalize_options()
[00:01:19]   File "setup.py", line 123, in finalize_options
[00:01:19]     overrides = ((k[5:].lower(), v) for k, v in os.environ.iteritems() if k.startswith('PYPI_'))
[00:01:19] AttributeError: '_Environ' object has no attribute 'iteritems'
[00:01:19] Command exited with code 1
```

**Comment by taschini** [comment]
Hopefully fixed.
