### ISSUE TITLE
I receive error during installation

### ISSUE THREAD

**Issue by ehsanq-1989** [taschini/pycrlibm#2]
I receive following message when i try to install crlibm, please help me:

```
C:\Users\Ehsan>pip install crlibm
Collecting crlibm
  Using cached crlibm-1.0.3.tar.gz
Installing collected packages: crlibm
  Running setup.py install for crlibm ... error
    Complete output from command C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ehsan\
\AppData\\Local\\Temp\\pip-build-xp2bsau_\\crlibm\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(comp
ile(code, __file__, 'exec'))" install --record C:\Users\Ehsan\AppData\Local\Temp\pip-fudvij99-record\install-record.txt --single-version-externally-managed --co
mpile:
    running install
    running build
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Ehsan\AppData\Local\Temp\pip-build-xp2bsau_\crlibm\setup.py", line 189, in <module>
        setup(**metadata)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\command\build_ext.py", line 308, in run
        force=self.force)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\ccompiler.py", line 1031, in new_compiler
        return klass(None, dry_run, force)
      File "C:\Users\Ehsan\AppData\Local\Temp\pip-build-xp2bsau_\crlibm\setup.py", line 58, in __init__
        cygwinccompiler.CygwinCCompiler.__init__(self, verbose, dry_run, force)
      File "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\lib\distutils\cygwinccompiler.py", line 126, in __init__
        if self.ld_version >= "2.10.90":
    TypeError: '>=' not supported between instances of 'NoneType' and 'str'

    ----------------------------------------
Command "C:\Users\Ehsan\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Ehsan\\AppData\\Local\\Temp\\p
ip-build-xp2bsau_\\crlibm\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exe
c'))" install --record C:\Users\Ehsan\AppData\Local\Temp\pip-fudvij99-record\install-record.txt --single-version-externally-managed --compile" failed with error
 code 1 in C:\Users\Ehsan\AppData\Local\Temp\pip-build-xp2bsau_\crlibm\
```

**Comment by thalesnunes** [comment]
Facing the same issue with Python 3.9
